version: 2.1

orbs:
  python: circleci/python@1.3.2
  docker: circleci/docker@1.5.0

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: chmod +x ./manage.py && ./manage.py test
          name: Test

  docker-deploy:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_IMAGE
          tag: latest
      - docker/push:
          image: $DOCKER_IMAGE
          tag: latest


workflows:
  main:
    jobs:
      - test
      - docker-deploy:
          requires:
            - test
