version: 2.1

orbs:
  python: circleci/python@0.2.1
  docker: circleci/docker@1.5.0

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: chmod +x ./manage.py && ./manage.py test
          name: Test

  docker-deploy:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_IMAGE
      - docker/push:
          image: $DOCKER_IMAGE


workflows:
  main:
    jobs:
      - test
      - docker-deploy:
          requires:
            - test
